theme = "onedark"

[editor]
evil = true
line-number = "relative"
cursorline = true
true-color = true


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
